#!/bin/bash

# Read the commit message from the file specified as the first argument
COMMIT_MSG_FILE=$1
COMMIT_MSG="$(cat "$COMMIT_MSG_FILE")"

# Regular expression to check if the commit message starts with 'fix:', 'feat:', etc
COMMIT_REGEX="^(fix|feat|doc|test):"

if ! [[ $COMMIT_MSG =~ $COMMIT_REGEX ]]; then
    exec 1>&2
    echo "ERROR: Commit message does not start with 'fix:', 'feat:', 'doc:', or 'test:'"
    exit 1
fi

exit 0