#!/bin/bash

# The first argument is the file that contains the commit log message.
COMMIT_MSG_FILE=$1

# Assuming the project name is the name of the root directory of your Git repository.
PROJECT_NAME="PROJ123"

# Append the project name to the commit message.
echo -e "\n-$PROJECT_NAME-" >> "${COMMIT_MSG_FILE}"

exit 0